name: CI

on:
  push:
    branches: [main]

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.ID }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.HOSTPORT }}
          script: |
            powershell -File C:\ws\gitWorkflow.ps1
