name: CI

on:
  push:
    branches: [main]

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull changes
        run: git pull origin main
      - name: Set permissions
        run: chmod +x ./gradlew && chmod -R +x .
      - name: Build JAR
        run: ./gradlew bootJar
      - name: ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: 172.18.248.211
          username: user
          password: 1234
          port: 22
          key: ${{ secrets.SSHKEY }}
      - name: Stop existing container
        run: docker stop $(docker ps -q -f name=dockerapp) 2>/dev/null || true
      - name: Get existing image name
        id: get_image_name
        run: CONTAINER_ID=$(docker ps -aq -f name=dockerapp); IMAGE_ID=$(docker inspect -f '{{ .Image }}' $CONTAINER_ID); echo "::set-output name=image_id::$IMAGE_ID"
      - name: Tag old image with timestamp
        run: docker tag $IMAGE_ID dockerapp:${{ steps.get_image_name.outputs.image_id }}-${{ runner.os }}-${{ github.run_id }}
      - name: Run Docker container
        run: docker run -d --name dockerapp -p 8080:8080 dockerapp:latest
