name: CI

on:
  push:
    branches: [main]

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.ID }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.HOSTPORT }}
          script: |
            cd C:\ws\docker-ci-cd
#           chmod +x ./gradlew
      - name: Build JAR
        run: ./gradlew bootJar
      # key: ${{ secrets.SSHKEY }}
      - name: Stop existing container
        run: docker stop $(docker ps -q -f name=dockerapp) 2>/dev/null || true
      - name: Build and Tag Docker Image
        id: get_image_name
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "::set-output name=IMAGE_TAG::$TIMESTAMP"
          docker build -t dockerapp:$TIMESTAMP .
      - name: Run Docker container
        run: docker run -d --name dockerapp -p 8080:8080 dockerapp:${{ steps.get_image_name.outputs.IMAGE_TAG }}